### ISSUE TITLE
Handling Missing & Loading Data States

### ISSUE THREAD

**Issue by jdrew1303** [eventbrite/britecharts#226]
Charts usually have more than one state available to them but when designed the only state taken into account is where data is available immediately and there are no gaps in the data. This leaves it to the developer to handle the state display and this usually results in one of two cases: either the state is not handled (the most common one) or there is no continuity in design between what the designer had intended (because they did not think about invalid/insufficient data or load time).

## Expected Behavior
- [ ] When you're waiting for data to load there should be feedback for the user that the data is loading. Similar to how facebook uses placeholders to show loading state:
![image](https://cloud.githubusercontent.com/assets/2535432/26070557/f126de9a-399c-11e7-8e17-d2e4a40acf74.png)

 
- [ ] When there is no data available you should show that to the user instead of displaying an empty chart. eg: 
![image](https://cloud.githubusercontent.com/assets/2535432/26070177/8eb57a88-399b-11e7-9cfe-7eb76a68a78e.png)

- [ ] The charts should be tolerant of missing data ranges and data points like so: 
![image](https://cloud.githubusercontent.com/assets/2535432/26070229/c54cf9f4-399b-11e7-8977-33526245ddb8.png)

## Current Behavior
Currently it is left to the developer to handle loading, data normalization, etc.

## Possible Solution
Have states for loading and no data that a developer can call when they receive an error/have no data or while they wait for data. Take a look through metricsgraphicsjs to see how they handle missing data ranges gracefully.

## Context
Ive been using [metricsgraphicsjs](https://www.metricsgraphicsjs.org/) for the past while. The feature set is great but the styling of britecharts out of the box if far superior. The ability to gracefully handle different states and providing feedback to users helps to increase the perceived performance of the page (we can render it straight away and use animations to let the user know whats happening).

Thanks for the great work. The API is a pleasure to work with. :+1:

**Comment by Golodhros** [comment]
Hi @jdrew1303 , thanks for the issue!

Thanks a lot for the kind words, we are really glad to be able to contribute back to the community and that other developers like you enjoy working with Britecharts!

Regarding the 'loading state' and 'empty state',  we actually thought about it before and decided to leave those out of Britecharts. The reason is that we consider that our users would have really different use cases and design requirements for those two cases, and covering all of them would be tricky and probably unnecessary.

It's absolutely true that the styling between the charts and the loading states could be different and thus downgrade the experience, and at the same time, we think that those loading and empty states should be closer to the styling of the rest of the UI.

Regarding the missing data, we haven't encounter that use case in our product (we are actually filling missing entries on the charts) but we are open to listen to our users if they think they need it. That's why I think the best approach would be to open a 'proposal' issue with the request of supporting missing data entries, and if people support it, we would think on including that into Britecharts. Does it make sense?

**Comment by Golodhros** [comment]
Closing this issue.
Missing data on lines is covered on #258. 
We won't do loading states for now.
