### ISSUE TITLE
Create a code styleguide for Britecharts

### ISSUE THREAD

**Issue by Golodhros** [eventbrite/britecharts#264]
We want to create a code styleguide for Britecharts that could make more straightforward code reviews, discussions and questions. It would be also helpful for new contributors that don't feel confortable about the way they are coding their solutions.

## Expected Behavior
We should have a code styleguide to reference when talking about code on PRs, issues and code reviews.

## Current Behavior
We do not have that.

## Possible Solution
Create a markdown file with some of those, including:
* Indentation 
* Margin convention
* Testing patterns
* Ternary vs multiple if-else
* General best practices

## Context
We want to make Britecharts a project that is easy to contribute to.

**Comment by gagoar** [comment]
It might be great if we could present some sort of structure for each coding style. 

I think the one we use for our coding style could work. its basic structure is:

- title (the term you would most likely call the code style, like *indentation*)

- motivation (reasons why this style exist)

- the good (how should look like)

- the bad (how should not look like)

- case study (if you see that might be a good idea to show the reasoning for it)

take a look at [this example](https://github.com/eventbrite/javascript/tree/master/general#ternary-statements)

**Comment by nobitagit** [comment]
Some of those points can be addressed by wiring up the `eslintrc.json` file to the build so that any PR that does not conform to the rules automatically fails as soon as it is opened.

It won't be possible to address all of the issues in that sense but it will certainly cut down the efforts on your side while doing code reviews.

Also, I noticed that the Contributing.md file could be in need of some updating from you guys. It mentions tasks like `npm run dev`that are not defined in the package, so perhaps this could be tackled as well.

**Comment by gagoar** [comment]
correct! whatever we can address with `eslint` should be done in that fashion, but I think here, there are several things that are more stylistic and not always easy to spot with `eslint`. (altho arguably you could do almost anything with eslint).

**Comment by Golodhros** [comment]
Related to this, I just created a PR to clean our eslint issues: https://github.com/eventbrite/britecharts/pull/312
