### ISSUE TITLE
Is it possible to choose the items order in Donut chart?

### ISSUE THREAD

**Issue by tonydtran** [eventbrite/britecharts#303]
Hi everyone,

I would like to show several items in the donut chart in a specific order.

Example:
`const data = [
  {
    quantity: 20,
    name: 'critical',
    id: 1
  },
  {
    quantity: 30,
    name: 'normal',
    id: 2
  },
  {
    quantity: 50,
    name: 'good',
    id: 3
  }
]` 

In this case, the "good" slice will be the first displayed in the donut in the clockwise rotation, then the "normal" slice and finally the "critical" slice, because briteCharts generates from the biggest slice to the smallest, right?

Is it possible to define my own order, like using the ids ? If it's the case, I didn't find how to do that in the documentation.

Sorry for my poor English and thank you for your help !

**Comment by Golodhros** [comment]
Hi @tonydtran, thanks for the issue!

So you are right, by default we are ordering the slices by quantity. The function that we use is called 'sortComparator'. In order to make this configurable, we could create an accessor for this variable, so it would allow to change that function and change the ordering algorithm.

You could do it yourself and create a PR or if you can wait we could tackle this at some point in the near future.

**Comment by tonydtran** [comment]
Actually I'm not skilled enough to do that so I can wait for an update. Maybe in few months if you didn't change that and I got enough skills, I would do that haha !

Thank you for your answer @Golodhros !

**Comment by nobitagit** [comment]
Wouldn't it be easier to just show the data in the order that the chart receives it? This would have many advantages:

- the user would have total control on the data order, any sorting would be possible
- simpler API for the end user and simpler docs
- simpler maintenance of britecharts for contributors
- lighter footprint in terms of size (this pr would be about removing code, not adding)
- remove all the sorting logic from the chart(s)

Also, i think this would follow much of the concepts that we all use anyway when building stateless components in React, Vue and the likes where the goal is components that simply display data rather than changing it.

**Comment by Golodhros** [comment]
Hi @nobitagit, 

Good call! Yeah, it makes sense from the point of view of the code. 

I will check with our designer @evb-sun, as at this point I am not sure about the context of the decision of ordering by slice size. I guess it will be OK.

Thanks!

**Comment by Golodhros** [comment]
So, I checked with @evb-sun  and we think we will prefer to keep the default order as it is and add the option to change it.

The resultant API would be something like:
   donut.forceOrderingFunction(fn);

where the fn would be something like:
    (a, b) => b.quantity + a.quantity

or similar.

**Comment by Golodhros** [comment]
Related: https://github.com/eventbrite/britecharts/issues/358

**Comment by dalerasrorov-eb** [comment]
https://github.com/eventbrite/britecharts/pull/409

**Comment by ISMAELMARTINEZ** [comment]
Is there a plan for adding this to GroupBarGraph? I am comparing data for 2 weeks and is pretty annoying to see "monday, tuesday, thursday, friday, saturday, sunday, wednesday"...
Will it be possible to add the option to disable the internal ordering?
Thanks

**Comment by Golodhros** [comment]
Hi @ISMAELMARTINEZ, thanks for the comment.

Your use case makes a lot of sense, we definitely should have this feature available in the group bar chart.

I just created this issue: https://github.com/eventbrite/britecharts/issues/511
If you could complete it with a codepen where this is seen (based on https://codepen.io/Britecharts/pen/EwoMXy) that would be awesome!
