### ISSUE TITLE
how to use britecharts without npm/require/umd

### ISSUE THREAD

**Issue by ehartford** [eventbrite/britecharts#306]
I don't have any npm/require/umd.

how can I use britecharts the old fashioned way?

I want to add a <script src="britecharts.min.js"> and just use it.

**Comment by mmartimo** [comment]
It is a bit buried in an i-frame of the CDN demo page...   but check the source here:  https://eventbrite.github.io/britecharts/cdn-iframe.html

Also read through #196 

The question I have is if there are any differences between the use of the CDN version and the fully documented API?

**Comment by Golodhros** [comment]
Hi @ehartford, thanks for the issue!

As @mmartimo rightly pointed out, you can check at the end of the comments on that issue, that will suggest you to use:
``` <script src="https://cdn.jsdelivr.net/npm/britecharts@1/dist/bundled/britecharts.min.js" type="text/javascript"></script>```

This script will attach a `britecharts` object to your `window` object in JavaScript. This will contain all the charts of britecharts. Check also the CDN example code in https://github.com/eventbrite/britecharts/blob/master/src/doc/html/cdn-iframe.html

@mmartimo, regarding the differences between the CDN version and the UMD version, at this moment the difference are some naming (we are going to fix that in #302). Also maybe you get some differences due to the fact that the CDN version is the one of the last release, while the docs describe the latest commit of the project. I will release soon, so this difference will be less.

**Comment by rwholey-eb** [comment]
Maybe we should move the burried demo page back out. it didnt use to be hidden down there. Or put a link somewhere more prominent on the main demos page.

**Comment by Golodhros** [comment]
@ehartford, did this solution work for you?

**Comment by ehartford** [comment]
yes, thank you!

**Comment by zfrenchee** [comment]
Thanks for opening this issue, @ehartford . Would love to see the source (https://github.com/eventbrite/britecharts/blob/master/src/doc/html/cdn-iframe.html) linked to on the demo page (https://eventbrite.github.io/britecharts/cdn.html)

**Comment by Golodhros** [comment]
Hi @zfrenchee, 
There is a link to that demo page in our homepage.

Cheers
