### ISSUE TITLE
Linked DonutCharts

### ISSUE THREAD

**Issue by davo** [eventbrite/britecharts#328]
I'm trying to connect the mouse events for two donut charts with the same name (group) but with different quantities.

My reference was the [donuts demo code](https://github.com/eventbrite/britecharts/blob/master/demos/demo-donut.js).

What I'm doing wrong?

## Demo
https://codepen.io/davo/pen/OjpGOm?editors=0010

**Comment by davo** [comment]
Image of reference of what I'm trying to achieve.

![246813610](https://user-images.githubusercontent.com/76307/29093029-54d5b49c-7c56-11e7-8870-ece092ab5c0d.png)

**Comment by davo** [comment]
I have a working version here, but I'm using d3.js events rather than the custom events from Britecharts.

`
d3.select('#pieChartCurrent')
    .select('.chart-group').selectAll('path')
    .attr('class', function(d) {
        return d.data.key;
    })
    .on('mouseover', function(d, i) {
      d3.select('#pieChartTarget')
        .select('.chart-group').selectAll("path." + d.data.key)
        .transition()
        .attr('d', d3.arc().outerRadius(185).innerRadius(140));
});
`

[https://framer.cloud/LvCDj](https://framer.cloud/LvCDj)

**Comment by Golodhros** [comment]
Hi @davo , thanks for opening this issue!

I have been playing with your codepen and got to this state: https://codepen.io/Golodhros/pen/YxVjeR?editors=0010 
It is not really working, and it seems this has to do with a bug already reported: https://github.com/eventbrite/britecharts/issues/291

We are doing something wrong in the logic that checks for an svg, making it create new charts instead of rerendering over the old one.

I will try to tackle this bug as soon as possible, I will keep you updated!

**Comment by Golodhros** [comment]
Hey @davo , I just updated that codepen with a hacky fix for this. 
By removing the svg from the container with:
```d3.select('.js-donut-container2 svg').remove();```
we can create something that looks a bit closer to what you needed.

Still, I will be tackling the bug ASAP!

**Comment by davo** [comment]
Thanks @Golodhros!

For the protoype I was building I ended using straight d3.js code with the dispatch() event.

`d3.select('#pieChartTarget').selectAll("path."+this.name).dispatch('mouseover')`

Here is the [Framer demo](https://framer.cloud/LvCDj/)

Looking forward to reimplement britecharts in near future.
