### ISSUE TITLE
Support for dynamic data push api

### ISSUE THREAD

**Issue by ahmadalibaloch** [eventbrite/britecharts#332]
Is there a way to push new data nodes into chart dynamically? Or updating the existing chart or specific data nodes but not redrawing.

## Expected Behavior
Something like `push(dataNode)`

**Comment by Golodhros** [comment]
Hi @ahmadalibaloch , thanks for creating the issue!

We have one bug, https://github.com/eventbrite/britecharts/issues/291, that has something to do with this. In theory, we should be able to update the data on the container and call the chart in order to get that result. 

Due to that bug, we are creating new charts. I will be tackling this issue ASAP, and in the meanwhile, you could remove the chart and draw it again as a workaround.

**Comment by Golodhros** [comment]
This is almost solved, calling:
    container.datum(newDataset).call(chartInstance);
will work in most of the charts. If not, please open an issue.
