### ISSUE TITLE
Coloring donut chart is broken when you have 8 parts.

### ISSUE THREAD

**Issue by piotrsucharski** [eventbrite/britecharts#355]
The default color palette for donut has 7 colors, when you render a donut with data.length of 8 (or colors.length + 1) then the first and the last entry is placed next to each other and colored in the same way

## Expected Behavior
The entries could not have the same colors if placed next to each other.

## Current Behavior
The data entries have the same colors when placed next to each other in the situation described above.
![not_enough_colors](https://user-images.githubusercontent.com/20358674/30476129-5a8a65f6-9a09-11e7-9f8a-5260b503bd0d.PNG)
)

## Steps to Reproduce (for bugs)
1. Create a donut chart with a data set containing colors.length + 1 entries

## Context
The chart looks confusing.

## Your Environment

* Version used: 2.0.1
* Browser Name and version: Chrome 60
* Operating System and version (desktop or mobile): Win 7x64 desktop

**Comment by Golodhros** [comment]
Hi @piotrsucharski, thanks for taking the time to open the issue!

This is like this by design, as we don't actually recommend having a donut chart of more than 5 segments. If that's your use case, we would recommend to use a horizontal bar chart to render that data.

That said, if you still need this, there are several workarounds. The first would be to use a different color schema, like the grey, orange, blueGreen, etc. Those have 9 different colors.

Another workaround would be to actually set a custom color schema with `.colorSchema()`. The input should be an array of colors in hex format (as strings).

Let me know if this worked for you.

**Comment by piotrsucharski** [comment]
Hi, @Golodhros .

Firstly I used the approach you suggested as a last workaround, but then you're still facing the problem if your 
`source.length === colorSchema.length +1`

So in the and I came up with more generic and safe solution:

```
if (this.source.length % Colors.length === 1) {
	const extendedColors = Colors.slice();
	         extendedColors.push(Colors[2]);

	this.instance.colorSchema(extendedColors);
}
```

So, in that special case I'm using the extended colorSchema by some different color which is neither first nor the second one in the colorSchema array.

**Comment by Golodhros** [comment]
I see, yeah, that sounds like a good solution.

**Comment by piotrsucharski** [comment]
Actually I did some more testing, and found out that due to the fact that you're sorting the dataset by quantity the additional color needs to be different from what you have in the base color set. So on line 3 from what I pasted above it should be:
`
 extendedColors.push('#<some color not existing on the selected schema>');
`
