### ISSUE TITLE
[question]How To Run BriteCharts Demo

### ISSUE THREAD

**Issue by Dieber** [eventbrite/britecharts#460]
Hi, I want to run the demo by using command: 

`"npm run demos:serve"`

then browser has open a website 0.0.0.0:8001 automatically (ERR_ADDRESS_INVALID ofcourse..

then I input localhost:8001, It shows Can not get /

so how to run this demo based on your source code (src) locally?
 
Thanks for you guys helping 🍡 

enviroment:

Hardware: Surface Pro 4

System: Win10 16299

NodeJS version: 8.9.2

npm version: 5.5.1

**Comment by Golodhros** [comment]
Hi @Dieber, thanks for the question.
I understand you are following the [Contributing guide](https://github.com/eventbrite/britecharts/blob/master/.github/CONTRIBUTING.md), right? I guess you need to run `yarn run docs` before in order to see something there.

Let me know if that helped, it is really important to us that contributing becomes easier.

**Comment by Dieber** [comment]
@Golodhros 
Thanks for your help.
It's my fault, I didn't see the Contributing guide link before.
