### ISSUE TITLE
Add .legendTextFunction to Donut Chart

### ISSUE THREAD

**Issue by mrbongiolo** [eventbrite/britecharts#481]
## Expected Behavior
Add a new `legendTextFunction` method on the API.

## Current Behavior
Right now `drawLegend` calls `text( () => '${obj.data.percentage}% ${obj.data.name}' )`.

## Possible Solution
The new method `legendTextFunction` should be used on `drawLegend`, it will be called with `obj.data`, so that the custom function can have access to the data.
By default it should display the same text that we have today.

## Context
Allowing the usage of a custom function will help in cases when someone doesn't want to show the `name` or might want to use `quantity` instead of the `percentage`, alongside other options.
By following the concepts of "convention over configuration" we should always provide a good default behavior, in this case the same "45% Something" that we have today, so that user can start using the lib easily, but allowing for different and complex scenarios by providing a good API to hook in custom methods.

**Comment by Golodhros** [comment]
This looks great @mrbongiolo, thanks for creating the issue!

I have only one comment. We called that text legend, but now in hindsight I think is a poor naming, especially as we have a Legend component. Basically, I would love to move out from that name, and at the same time I don't know how we should call it.

Maybe 'centerText'? Or 'centerLabel'? Any suggestion will be appreciated.

**Comment by mrbongiolo** [comment]
@Golodhros Yeah, 'text legend' might be confusing.

In this case I prefer 'centerText' over 'centerLabel', since 'label' is used on the data as well and it could be confusing.

TBH, since I started using the lib the `nameLabel` and `valueLabel` methods always seemed a bit odd, they aren't quite right in point on what they do, without the docs at first I thought they were some kind of label element.

Wouldn't it be better to be "stricter" with the data schema? A BarChart should always have at least the `name` and `value` fields (any other fields should use other names and would be accessible in some functions, etc) , it's better to transform the data before sending it to the chart, than naming the `name` field as `something` and then ask the chart to use `something`.
This would allow the usage of the term `label` like an element. What do you think? I know this would require some changes and a new version that isn't backwards compatible, but it would make things clearer.

**Comment by Golodhros** [comment]
@mrbongiolo that's a good point about the 'nameLabel' and 'valueLabel'. The presence of those options in the API is something that since the beginning I have doubted.

In my mind, from the point of view of engineering and API correctness, they are almost an aberration. The data schema should be fixed, and our users would need to do the data transformations they need to follow that schema.

Now, from the point of view of a non-tech savvy user (designer, code aficionado, etc.), those classes can help them get started with Britecharts almost immediately. They let them use info that comes from third party sources directly, without having to code anything and making the library more accessible and flexible.

Getting to the root of it, we don't know where the bulk our users are in those two groups. Do they hate those options (we could remove it in the next major release), are they confused by them (that could be solved by better docs or better naming)?

What I can do now is to move your comments and my response to a different issue and see what other contributors and users think about it. Also, I have been thinking about doing a survey; this should be one of the questions.

**Comment by Golodhros** [comment]
@mrbongiolo I moved the label issue here https://github.com/eventbrite/britecharts/issues/482

**Comment by mrbongiolo** [comment]
@Golodhros Nice. In this case I guess we should name it `centerText` and `centerTextFunction`?

**Comment by Golodhros** [comment]
That sounds good to me!

**Comment by dalerasrorov-eb** [comment]
@mrbongiolo thanks for opening the issue! It was implemented in https://github.com/eventbrite/britecharts/pull/498, let us know if you have any issue.
