### ISSUE TITLE
Donut chart empty slice does not update

### ISSUE THREAD

**Issue by chinaowl** [eventbrite/britecharts#484]
## Expected Behavior

When I create a donut chart with the `showEmptySlice` setting, start with empty data and then refresh with actual data, I should see the donut chart with the correct data.

## Current Behavior

I created a donut chart using `emptyDataConfig` with `showEmptySlice` set to true. When I display the chart with data with quantity totaling zero, I see the empty chart as expected. However, I then refresh the chart with new data with quantity > 0. I can see the animation, but the chart still appears empty for some reason. It works if I immediately display a chart with non-empty data.

## Steps to Reproduce (for bugs)

Here is a minimal Pen: https://codepen.io/chinaowl/pen/goKGwz. You can comment out line 20 to see what I mean about the chart working if I don't start with an empty state.

## Context

I'm creating a live poll and displaying the results with the donut chart. In the beginning, there are no responses so I show the empty donut chart. I update the chart every time a response comes in, and even though the data I'm passing in has quantity > 0, the chart remains empty.

## Your Environment

* Version used: 2.4.11
* Browser Name and version: Chrome 63

**Comment by Golodhros** [comment]
Hi @chinaowl  thanks for taking the time to open an issue!

With the current API, the empty slice configuration overrides the data that you pass. Are you are using the same instance of the chart, the value given to that property hasn't changed, so the chart renders the empty slice again. 

In order to see your new data, you need to explicitly deactivate the empty slice option, check this Pen: https://codepen.io/Britecharts/pen/ypEpXq

Removing the previous and creating a new chart would work too.

Let me know if that works!

**Comment by chinaowl** [comment]
Thank you for the example code, it works now!

**Comment by Golodhros** [comment]
Glad it worked for you!
