### ISSUE TITLE
Line chart X Axis issue with monthly data

### ISSUE THREAD

**Issue by DamonCool** [eventbrite/britecharts#618]
When providing monthly data to the chart without a timestamp, the chart changes the value for the beginning of the month to the end of the previous month.

## Expected Behavior
Axis should render on the date specified and should not require a time component.

## Current Behavior
Dates provided in the format 2018-01-01 will render as 2017-12-31

## Possible Solution
Adding in a timestamp to the date 2018-01-01T12:00:00Z seems to resolve the issue.

## Steps to Reproduce (for bugs)
https://codepen.io/damoncool/pen/GdwvQK

## Context
Strange unexpected behavior.

## Your Environment
https://codepen.io/damoncool/pen/GdwvQK

**Comment by Golodhros** [comment]
Hi @DamonCool, thanks for opening this issue!

That's an interesting outcome. We have had some issues before due to the different date formats and how browsers deal with them (using their own new Date() implementation). Actually, you will see how your codepen example doesn't even work in Firefox.

This is a muddy spot where we will need to do some extensive testing to see what is and what is not supported as date formats. What we could do though, is to be super specific when defining the date formats in our docs, so that everybody uses the same formats and we get more consistent and bug-free results.

Thanks a lot for surfacing this issue!

**Comment by DamonCool** [comment]
Hi @Golodhros ,

Thanks for the quick response.   

I've added a time offset variable to the codepen and you can see that under 8 hours will give unexpected results.  Seems to be a timezone issue.  I'm guessing there is a mixture of GMT(epoch) and local (browser) time in some date math. 

If it is a mixture of local time versus GMT in your code, then a specific format would be based on each users timezone, and for their local time.  For companies that have users in multiple timezones, it wouldn't be correct for everyone.  It would probably only be correct for the timezone that the BI team is in.

I'm surprised that this hasn't been noticed before.  Maybe you run your reporting all from GMT?

Not sure about firefox, I don't see any console errors besides a few CORS issues with fonts from coderpen.

**Comment by Golodhros** [comment]
Hi @DamonCool, thanks for the follow up!

Actually, we use this charts with different time zones, so I am surprised to see that it is failing under 8 hours.

I still think there is something wrong with that code, as it is not working in Firefox.

I will try to find some time to look at this in more detail, thanks a lot!

**Comment by Golodhros** [comment]
Hi @DamonCool,

It seems that yes, if we don't pass a specific timestamp, the date is going to be converted to GMT by the browser.

The solution is to always add a timestamp. I will try to add it to the docs somewhere.

Thanks!
