### ISSUE TITLE
Add a xAxisLabel and yAxisLabel for Bar Chart

### ISSUE THREAD

**Issue by Golodhros** [eventbrite/britecharts#629]
## Expected
We will allow users to add labels to the axis on the bar chart, the same way we do for the step chart.

**Comment by iamkk11** [comment]
This feature will be greatly appreciated. Looking forward to it

**Comment by dalerasrorov-eb** [comment]
@iamkk11 it should be available now in the new release 2.9.11. Let us know if there is an issue.

**Comment by iamkk11** [comment]
Hi @dalerasrorov-eb  its not working see below error message.
×
Error: Method not supported by Britechart: xAxisLabel yAxisLabel

my package.json is:

   "britecharts": "^2.9.1",
    "britecharts-react": "^0.4.1",

**Comment by dalerasrorov-eb** [comment]
@iamkk11 Sorry to hear that. I tried to use the latest britecharts bundle and had those new functions available with no issue. Try doing `yarn install` first and try again. If that doesn't work, removing `node_modules` folder: `rm -r node_modules` and then `yarn install`. I think that the updates didn't go through due to cache or other reasons. Let me know if those didn't work. Thanks!

**Comment by iamkk11** [comment]
@dalerasrorov-eb  i did npm start -- --reset cache to no avail.. I am using npm

**Comment by miglesiasEB** [comment]
It works well for me: https://codepen.io/Britecharts/pen/yEwpeg?editors=1010

Just to make sure @iamkk11, you are trying to add labels in the bar chart, right?
