### ISSUE TITLE
Tooltip is opened outside of viewbox even when there is space

### ISSUE THREAD

**Issue by rickardliljeberg** [eventbrite/britecharts#689]
As indicated on this screenshot my tooltip is opened outside of the viewbox even tho there is space on the left hand side.
![image](https://user-images.githubusercontent.com/3726818/47787040-eb7dbe80-dd0d-11e8-8650-8cfff6b2ce46.png)

I cannot replicate this on a actual phone because on actual phones I cannot get the tooltip to display at all (a separate issue I will dig into).

The codepen here should trigger the problem: https://codepen.io/anon/pen/QZXmaJ
However due to how codepen you cannot make the page scale down like this (like chromes device-mode).
But the code in a loose html file should give the behaviour.

**Comment by Golodhros** [comment]
Hi @rickardliljeberg,

Usually in mobile there is no space for the tooltips. That's why we provide the `tooltipThreshold` property, so you can hide them when there is not enough real state for it. Check the API here http://eventbrite.github.io/britecharts/module-Stacked-area.html#.tooltipThreshold__anchor
