### ISSUE TITLE
Data points not aligning correctly in line chart on hover

### ISSUE THREAD

**Issue by ronvenna** [eventbrite/britecharts#697]
## Expected Behavior
Horizontal scale should match the data point on hover on a line chart. 

## Current Behavior
Horizontal scale does not match the data point on hover on a line chart. 

## Steps to Reproduce (for bugs)

1. Create a Line chart with tooltip
2. Plug in less than 10 data points 
3. Hover over

## Screenshots (if appropriate):
<img width="1204" alt="screenshot 2019-01-15 16 30 50" src="https://user-images.githubusercontent.com/2246772/51218916-4a9da900-18e3-11e9-9550-9caf36b08765.png">

## Context
Cannot use on production with this behavior

## Your Environment

* Version used:  britecharts@2.8.0
* Browser Name and version: Chrome v71
* Operating System and version: Mac OSX Mojave
* Link to your project or codepen: None

**Comment by Golodhros** [comment]
Hi @ronvenna, thanks for creating this issue!

I am afraid what you ask is not possible with D3.js. We have a good amount of control over the look of our charts, but the control of the axes is somewhat limited. 
It also happens that the axis doesn't know anything about your data points, it only knows the min and max value, and it will create the ticks between those values as it sees fit.
A possible workaround would be to use the `xTicks` option (http://eventbrite.github.io/britecharts/module-Line.html#.xTicks__anchor) to set a good amount of ticks, so that maybe you get to a point where there are one tick for each of your datapoints. This again is not exact, as D3.js will decide where to place the ticks.

Thanks for using Britecharts!
