### ISSUE TITLE
Increase line chart date range (X axis)

### ISSUE THREAD

**Issue by shayh** [eventbrite/britecharts#739]
## Expected Behavior
I would like the graph to supply the full range of my query to the server, however some times the data is available for part of the request date range.
to increase the graph range i'm adding null data points in the beginning and end of the dates array. my expectation is the graph too display the full dates range while drawing a line only to valid data points.

## Current Behavior
currently line chart would treat the null as 0 and connect the null point to the first valid point.

## Possible Solution
null point shouldn't be part of the chart SVG path

## Steps to Reproduce
add a null data point to the dates series array of a line chart
https://codepen.io/shayh/pen/JQrGpq

## Screenshots (if appropriate)
![image](https://user-images.githubusercontent.com/366321/60172214-e7f6f480-9814-11e9-81ee-4857c1945cf6.png)

## Your Environment

* Britecharts version used: 2.11.0
* Browser Name and version: Firefox latets
* Operating System and version: linux
* Link to your project or codepen: https://codepen.io/shayh/pen/JQrGpq

**Comment by Golodhros** [comment]
Hi @shayh, thanks for opening this issue!

I understand what is happening, and the behavior you see when adding null data entries, that is the expected behavior at this point. 

I think that what you really want here is for us to mark missing values somehow, or to handle them gracefully. We have a proposal regarding this feature: https://github.com/eventbrite/britecharts/issues/258

Please mention your support to that proposal in the GitHub issue. Hopefully, we could get to it sometime soon. I will close this issue for now.

**Comment by shayh** [comment]
thanks
